insert into classifica values(1,'Zatch Bell');
insert into classifica values(2,'Brago');
insert into classifica values(3,'Clear Note');
insert into classifica values(4,'Ponygon');
insert into classifica values(5,'Tia');
insert into classifica values(6,'Gorm');
insert into classifica values(7,'Kanchome');
insert into classifica values(8,'Purio');
insert into classifica values(9,'Ashuron');
insert into classifica values(10,'Earth');
insert into classifica values(11,'Rogue Viper');
insert into classifica values(12,'Zeno Bell');
insert into classifica values(13,'Rodeaux');
insert into classifica values(14,'Cherish');
insert into classifica values(15,'Jedun');
insert into classifica values(16,'Momon');
insert into classifica values(17,'Karudio');
insert into classifica values(18,'Vincent Bari');
insert into classifica values(19,'Keith');
insert into classifica values(20,'Ted');
insert into classifica values(21,'Gyaron');
insert into classifica values(22,'Riya');
insert into classifica values(23,'Zaruchimu');
insert into classifica values(24,'Fango');
insert into classifica values(25,'Wonrei');
insert into classifica values(26,'Riou');
insert into classifica values(27,'Buzurai');
insert into classifica values(28,'Hougan');
insert into classifica values(29,'Elzador');
insert into classifica values(30,'Rein');
insert into classifica values(31,'Coral Q');
insert into classifica values(32,'Akatsuki');
insert into classifica values(33,'Zofis');
insert into classifica values(34,'Penny');
insert into classifica values(35,'Byonko');
insert into classifica values(36,'Kido');
insert into classifica values(37,'Hyde');
insert into classifica values(38,'Baransha');
insert into classifica values(39,'Donpoccho');
insert into classifica values(40,'Bago');
insert into classifica values('41-70','Rops');
insert into classifica values('41-70','Baltro');
insert into classifica values('41-70','Yopopo');
insert into classifica values('41-70','Kikuropu');
insert into classifica values('41-70','Maruss');
insert into classifica values('41-70','Pokkerio');
insert into classifica values('41-70','Danny');
insert into classifica values('41-70','Zoboron');
insert into classifica values('41-70','Zabas');
insert into classifica values('71-100','Reikom');
insert into classifica values('71-100','Gofure');
insert into classifica values('71-100','Sugino');
insert into classifica values('71-100','Kolulu');
insert into classifica values('71-100','Fein');
insert into classifica values('71-100','Eshros');
insert into classifica values('71-100','Furigaro');
insert into classifica values('71-100','Robnos');
