insert into episodi values (1, "Il ragazzo del fulmine");
insert into episodi values (2, "Incantesimo di ghiaccio");
insert into episodi values (3, "Il secondo incantesimo");
insert into episodi values (4, "La battaglia dei Mamodo");
insert into episodi values (5, "Il Mamodo oscuro");
insert into episodi values (6, "La sparizione del libro rosso");
insert into episodi values (7, "Follia Botanica");
insert into episodi values (8, "Una Mamodo gentile");
insert into episodi values (9, "Il terzo incantesimo");
insert into episodi values (10, "L'élite dei Mamodo");
insert into episodi values (11, "Folgore l'invincibile");
insert into episodi values (12, "Il passato di Sherry");
insert into episodi values (13, "La rivincita");
insert into episodi values (14, "La ragazzina e la popstar");
insert into episodi values (15, "Un nuovo patto");
insert into episodi values (16, "L'invulnerabile Robnos");
insert into episodi values (17, "Sorpresa al curry");
insert into episodi values (18, "Tutti a Londra");
insert into episodi values (19, "Il castello maledetto");
insert into episodi values (20, "I fiori del male");
insert into episodi values (21, "Un altro Zatch");
insert into episodi values (22, "Il Mamodo che danza");
insert into episodi values (23, "Vai, Ponygon!");
insert into episodi values (24, "Apollo il viaggiatore 1ª parte");
insert into episodi values (25, "Apollo il viaggiatore 2ª parte");
insert into episodi values (26, "Una giornata con Zatch");
insert into episodi values (27, "Danny Boy");
insert into episodi values (28, "L'avventura di Tia e Megumi");
insert into episodi values (29, "La battaglia al parco dei divertimenti");
insert into episodi values (30, "Zatch e Tia fanno squadra");
insert into episodi values (31, "Una nuova graziosa studentessa");
insert into episodi values (32, "Il segreto di Shion");
insert into episodi values (33, "La ricomposizione dello specchio");
insert into episodi values (34, "Lacrime al tramonto");
insert into episodi values (35, "L'ultima battaglia per lo specchio");
insert into episodi values (36, "Zatch contro Naomi");
insert into episodi values (37, "Battaglia ad Hong Kong 1ª parte");
insert into episodi values (38, "Battaglia ad Hong Kong 2ª parte");
insert into episodi values (39, "Il cacciatore invisibile");
insert into episodi values (40, "Kanchome fratello maggiore");
insert into episodi values (41, "Kanchome l'invincibile");
insert into episodi values (42, "Nemici freddi come il ghiaccio");
insert into episodi values (43, "Joe Mantide:l'eroe della giustizia");
insert into episodi values (44, "Sfida a duello");
insert into episodi values (45, "Zatch contro Bari");
insert into episodi values (46, "Chiamata per Ponygon");
insert into episodi values (47, "Ruggiti nella neve");
insert into episodi values (48, "Il mistero delle tavole di pietra");
insert into episodi values (49, "Il Dottor Rebus e i magnifici 12");
insert into episodi values (50, "Il sesto incantesimo");
insert into episodi values (51, "Il mamodo con la maschera");
insert into episodi values (52, "Il mio amato Zatch");
insert into episodi values (53, "So Giaku, il drago d'acqua");
insert into episodi values (54, "Zatch contro Kiyo");
insert into episodi values (55, "Il ritorno di Penny");
insert into episodi values (56, "Saifogeo! La luce della speranza");
insert into episodi values (57, "I padroni del silenzio");
insert into episodi values (58, "Tutti contro Milordo Z");
insert into episodi values (59, "Il ritorno di Folgore");
insert into episodi values (60, "Nel labirinto del nemico");
insert into episodi values (61, "Incantesimo di Dolore");
insert into episodi values (62, "Il magnifico Victoream!");
insert into episodi values (63, "L'ira di Victoream'");
insert into episodi values (64, "La battaglia sulla sabbia");
insert into episodi values (65, "Ponygon, veloce come il fulmine");
insert into episodi values (66, "Il libro rosso della promessa");
insert into episodi values (67, "Il ritorno dei magnifici dodici");
insert into episodi values (68, "La confessione di Tia");
insert into episodi values (69, "Nella tela di Zofis");
insert into episodi values (70, "I quattro mamodo supremi");
insert into episodi values (71, "Il coraggio di Wonrei");
insert into episodi values (72, "Il terribile Belgim");
insert into episodi values (73, "Dottor Rebus, sarai sempre il mio re");
insert into episodi values (74, "Pamoon, il guerriero celeste");
insert into episodi values (75, "Liberati da mille anni di sofferenze");
insert into episodi values (76, "Il ritorno del perfido Zofis");
insert into episodi values (77, "Il ritorno di Sherry e Brago");
insert into episodi values (78, "La grande paura di Laila");
insert into episodi values (79, "L'ultimo dei quattro mamodo supremi'");
insert into episodi values (80, "Demolt, il guerriero pazzo!");
insert into episodi values (81, "Vinceremo ad ogni costo");
insert into episodi values (82, "L'addio di Penny'");
insert into episodi values (83, "Zagurzem, il settimo incantesimo!");
insert into episodi values (84, "La battaglia finale con Demolt!");
insert into episodi values (85, "Il segreto di Koko");
insert into episodi values (86, "Tutti uniti contro Zofis!");
insert into episodi values (87, "Salviamo Koko");
insert into episodi values (88, "Un nuovo Addio");
insert into episodi values (89, "Il ritorno del magnifico Sir Victoream");
insert into episodi values (90, "Compito in classe a sorpresa");
insert into episodi values (91, "Il perfido piano di Naomi");
insert into episodi values (92, "Il dottor Rebus ritrova la speranza");
insert into episodi values (93, "Il richiamo");
insert into episodi values (94, "Il portale dei mondi");
insert into episodi values (95, "L'esercito di ferro'");
insert into episodi values (96, "Brago all'attacco... senza Sherry'");
insert into episodi values (97, "La vendetta di Magister");
insert into episodi values (98, "Battaglia decisiva nell'intermondo");
insert into episodi values (99, "L'impagabile signorina Moina!");
insert into episodi values (100, "La triste cornamusa di Nicholas");
insert into episodi values (101, "Il ragazzo che parla al vento");
insert into episodi values (102, "La minaccia del Bao Zakeruga");
insert into episodi values (103, "Il profumo di Cherish");
insert into episodi values (104, "Suzy contro Megumi");
insert into episodi values (105, "Il robot Coral Q!");
insert into episodi values (106, "Il contrattacco di Coral Q");
insert into episodi values (107, "Il nuovo Bao Zakeruga");
insert into episodi values (108, "Nostalgia di casa");
insert into episodi values (109, "Duello nelle terre del nord");
insert into episodi values (110, "Ponygon contro Karudio");
insert into episodi values (111, "Un grande aeroporto!");
insert into episodi values (112, "Pattinaggio sul ghiaccio");
insert into episodi values (113, "Una lettera da un amico");
insert into episodi values (114, "La grande debolezza di Kyle");
insert into episodi values (115, "Il terribile Rodeaux!");
insert into episodi values (116, "Il desiderio di Rein");
insert into episodi values (117, "Il Kung fu della passione");
insert into episodi values (118, "Il rapimento di Zatch");
insert into episodi values (119, "Megumi, la sola e unica partner!");
insert into episodi values (120, "Due nuovi compagni");
insert into episodi values (121, "Chagiru Saifodon, il sesto incantesimo di Tia!");
insert into episodi values (122, "Kaguya, la ragazza che ritorna alla luna");
insert into episodi values (123, "Ted contro Bari");
insert into episodi values (124, "Premonizione di separazione");
insert into episodi values (125, "Riou senza cuore");
insert into episodi values (126, "Un viaggio da cui non puoi più tornare");
insert into episodi values (127, "Arrivati da Faudo");
insert into episodi values (128, "Il coraggio di Kanchome");
insert into episodi values (129, "Dima Buruk, il nuovo incantesimo di Kanchome!");
insert into episodi values (130, "Bao contro Dioga");
insert into episodi values (131, "La scelta di Zatch");
insert into episodi values (132, "Dentro il Faudo");
insert into episodi values (133, "La verità sulla maledizione");
insert into episodi values (134, "Decisi a soffrire");
insert into episodi values (135, "Le lacrime di Momon");
insert into episodi values (136, "Le rivalità bloccano il passaggio");
insert into episodi values (137, "La distruzione del Sigillo!");
insert into episodi values (138, "Faudo, Il mamodo gigante!");
insert into episodi values (139, "Rientro disperato");
insert into episodi values (140, "Li Yen, ti proteggerò per sempre!");
insert into episodi values (141, "Karudio e Ponygon fanno squadra");
insert into episodi values (142, "La stanza sigillata");
insert into episodi values (143, "Il guerriero Alishie");
insert into episodi values (144, "Siamo noi i Re!");
insert into episodi values (145, "Ted contro Cherish");
insert into episodi values (146, "L'addio di Earth");
insert into episodi values (147, "L'imperatore del fulmine Zeno!");
insert into episodi values (148, "Due diversi destini");
insert into episodi values (149, "Zatch contro Zeno");
insert into episodi values (150, "La battaglia finale contro il Faudo");