insert into mamodomillenari values (1, "Goren", "laser", 4, "Maurice", "grigio", "Dauwan Bell");
insert into mamodomillenari values (2, "Fantamu", "vento", 1, "Shiruba", "grigio scuro", "Zatch Bell");
insert into mamodomillenari values (3, "Bahking", "rafforzamento", 1, "Sari", "blu opaco", "Brago");
insert into mamodomillenari values (4, "Goramu", "rafforzamento", 1, "Unknown", "marrone", "Zofis");
insert into mamodomillenari values (5, "Reiza", "metallo", 2, "Roza", "caco", "Zatch Bell");
insert into mamodomillenari values (6, "Ibaris", "sabbia", 2, "Kyle Pikaru", "marrone chiaro", "Brago");
insert into mamodomillenari values (7, "Babiru", "energia", 2, "Seiu ou", "viola chiaro", "Brago");
insert into mamodomillenari values (8, "Kalura", "pianta", 2, "Marlene Yanenz", "blu oltremare", "Kido");
insert into mamodomillenari values (9, "Bora Bora", "metallo", 2, "Henry Abbolt", "blu", "Tia");
insert into mamodomillenari values (10, "Dogmos", "terra", 2, "Paul Kahn", "marrone", "Zatch Bell");
insert into mamodomillenari values (11, "Erujo", "laser", 4, "Francoise Cardan", "verde mente", "Brago");
insert into mamodomillenari values (12, "Badios", "laser", 2, "Charmy", "giallo chiaro", "Brago");
insert into mamodomillenari values (13, "Alm", "energia", 5, "Mamiko", "blu polvere scura", "Zatch Bell");
insert into mamodomillenari values (14, "Fausto", "energia", 4, "Natsuo Costner", "verde acqua", "Brago");
insert into mamodomillenari values (15, "Tsuvai", "catene", 4, "Divitto Cole", "marrone", "Brago");
insert into mamodomillenari values (16, "Torowa", "laser", 4, "Ozzie Bryant", "pesca", "Brago");
insert into mamodomillenari values (17, "Ikagesso", "acqua", 0, "Pauza", "cacao", "Brago");
insert into mamodomillenari values (18, "Zakson", "unknown", 0, "Carter", "viola prugna", "Brago");
insert into mamodomillenari values (19, "Isojin", "gravita", 0, "Karamanris", "grigio antracite", "Brago");
insert into mamodomillenari values (20, "Gelios", "armatura", 4, "John Owen", "lime", "Tia");
insert into mamodomillenari values (21, "Hajime", "unknown", 0, "Anna", "verde giallo intenso", "Zatch Bell");
insert into mamodomillenari values (22, "Ganz", "rafforzamento", 2, "Billy Ferris", "grigio scuro", "Kanchome");
insert into mamodomillenari values (23, "Ferius", "fuoco", 0, "Sebastian", "verde foresta", "Brago");
insert into mamodomillenari values (24, "Jobin", "ghiaccio", 1, "Yuga", "marrone chiaro", "Brago");
insert into mamodomillenari values (25, "Bamu", "energia", 2, "Luke Brown", "grullo", "Brago");
insert into mamodomillenari values (26, "Victoream", "laser", 6, "Mohawk Ace", "blu forte", "Kanchome");
insert into mamodomillenari values (27, "Laila", "luna", 6, "Albert", "viola", "Zatch Bell");
insert into mamodomillenari values (28, "Dalmos", "bomba", 8, "Elizabeth", "grigio", "Ponygon");
insert into mamodomillenari values (29, "Paramakion", "vento", 1, "Warren", "beige", "Kido");
insert into mamodomillenari values (30, "Urimire", "unknown", 0, "John", "giallo chiaro", "Brago");
insert into mamodomillenari values (31, "Mirako", "unknown", 0, "Jackson Bay", "grigio chiaro", "Brago");
insert into mamodomillenari values (32, "Dekofis", "fuoco", 1, "Binder Rude", "iris", "Brago");
insert into mamodomillenari values (33, "Mukaron", "unknown", 0, "Heather Spoon", "oliva", "Ponygon");
insert into mamodomillenari values (34, "Baraho", "armatura", 1, "Takos", "verde", "Brago");
insert into mamodomillenari values (35, "Payom", "unknown", 0, "Biarham", "ocra", "Brago");
insert into mamodomillenari values (36, "Zami", "rafforzamento", 1, "Tongari", "prugna", "Brago");
insert into mamodomillenari values (37, "Ninin", "energia", 1, "Kari", "blu profondo", "Brago");
insert into mamodomillenari values (38, "Gein", "laser", 0, "Yoshinori", "biondo", "Brago");
insert into mamodomillenari values (39, "Domu", "sabbia", 0, "Yu", "viola vivido", "Brago");
insert into mamodomillenari values (40, "Meumutsume", "unknown", 0, "Dan", "marrone chiaro", "Brago");
insert into mamodomillenari values (41, "Zurai", "unknown", 0, "Haydn", "rosso porpora vivido", "Brago");
insert into mamodomillenari values (42, "Noumen", "rafforzamento", 1, "Kinjou", "mattone", "Brago");
insert into mamodomillenari values (43, "Buton", "rafforzamento", 1, "Aram", "mela verde", "Brago");
insert into mamodomillenari values (44, "Minorusam", "water", 1, "Kakoyanis", "verde", "Brago");
insert into mamodomillenari values (45, "Giriko", "metallo", 1, "Wan Yin", "colza", "Brago");
insert into mamodomillenari values (46, "Hoibun", "unknown", 0, "Sadato", "caramella verde", "Brago");
insert into mamodomillenari values (47, "Gamelle", "unknown", 0, "Sagan", "ruggine", "Brago");
insert into mamodomillenari values (48, "Nyobiio", "unknown", 0, "Norris", "blu vivido", "Brago");
insert into mamodomillenari values (49, "Kamakku", "luce", 3, "Raion", "marrone", "Kido");
insert into mamodomillenari values (50, "Pamoon", "stella", 10, "Lance", "giallo cobalto", "Zofis");
insert into mamodomillenari values (51, "Belgim E.O", "fantasma", 6, "Dalia Anje", "arancione scuro", "Kido");
insert into mamodomillenari values (52, "Tsao-Lon", "arti marziali", 4, "Gensou", "verde scuro", "Wonrei");
insert into mamodomillenari values (53, "Demolt", "armatura", 8, "Roberto Vile", "viola scuro", "Wonrei");
insert into mamodomillenari values (54, "Dauwan Bell", "fulmine", 18, "Willy", "unknown", "-");