insert into mamodo values (1, 'Zatch Bell', 'fulmine', '15', 'Kiyomaro Takamine', 'rosso', '-');
insert into mamodo values (2, 'Zeno Bell', 'fulmine', '14', 'Dufort', 'argento', 'Zatch Bell');
insert into mamodo values (3, 'Tia', 'scudo', '10', 'Megumi Oumi', 'vermiglio', 'Clear Note');
insert into mamodo values (4, 'Kanchome', 'trasformazione', '8', 'Parco Folgore', 'giallo', 'Clear Note');
insert into mamodo values (5, 'Ponygon', 'armatura' , '9', 'Kafk Sunbeam', 'salmone', 'Tia');
insert into mamodo values (6, 'Wonrei', 'arti marziali', '16', 'Li-en', 'viola reale', 'Tia');
insert into mamodo values (7, 'Kido', 'meccanico', '12', 'Dr. Riddle', 'grigio', 'Mamodo Millenari');
insert into mamodo values (8, 'Brago', 'gravita', '19', 'Sherry Belmont', 'nero', 'Zatch Bell');
insert into mamodo values (9, 'Hyde', 'vento', '6', 'Eido', 'verde oceano', 'Mamodo Millenari');
insert into mamodo values (10, 'Reycom', 'ghiaccio', '6', 'Hosokawa', 'blu', 'Zatch Bell');
insert into mamodo values (11, 'Gofure', 'terra', '2', 'Renji', 'marrone chiaro', 'Zatch Bell');
insert into mamodo values (12, 'Sugino', 'pianta', '6', 'Haru' , 'verde chiaro', 'Zatch Bell');
insert into mamodo values (13, 'Kolulu', 'artiglio', '7', 'Lori' , 'rosa', 'Zatch Bell');
insert into mamodo values (14, 'Fein', 'vento', '6', 'Sebe', 'viola chiaro', 'Zatch Bell');
insert into mamodo values (15, 'Eshros', 'terra', '8', 'Shin', 'marrone', 'Zatch Bell');
insert into mamodo values (16, 'Maruss', 'metallo', '6', 'Rembrant', 'grigio scuro', 'Zatch Bell');
insert into mamodo values (17, 'Robnos', 'laser', '7', 'Ruku', 'turchese', 'Zatch Bell');
insert into mamodo values (18, 'Baltro', 'pianta', '2', 'Steng', 'verde muschio', 'Zeno Bell');
insert into mamodo values (19, 'Yopopo', 'musica', '3', 'Djem', 'verde', 'Kikuropu');
insert into mamodo values (20, 'Kikuropu', 'rafforzamento', '4', 'British  Gentleman', 'viola reale scuro', 'Yopopo');
insert into mamodo values (21, 'Zofis', 'esplosione', '8', 'Koko', 'magenta', 'Brago');
insert into mamodo values (22, 'Pokkerio', 'pianta', '3', 'Periko', 'marrone scuro', 'Brago');
insert into mamodo values (23, 'Rops', 'catene', '4', 'Apollo', 'azzurro', 'Zeno Bell');
insert into mamodo values (24, 'Danny', 'guarigione', '1', 'Mr. Goldo', 'viola', 'Zatch Bell');
insert into mamodo values (25, 'Purio', 'melma', '9', 'Lupa', 'turchese chiaro', 'Clear Note');
insert into mamodo values (26, 'Zoboron', 'energia', '2', 'Hige', 'marrone', 'Zatch Bell');
insert into mamodo values (27, 'Nya', 'rafforzamento', '4', 'Shion', 'rosa pallido', 'Grisor');
insert into mamodo values (28, 'Cut N Paste', 'forbici', '6', 'Kiichiro', 'grigio chiaro', 'Zatch Bell');
insert into mamodo values (29, 'Grisor', 'fuoco', '7', 'Dr. Hakase', 'prugna', 'Zatch Bell');
insert into mamodo values (30, 'Zabas', 'vento', '2', 'Galliont', 'grigio-blu', 'Zatch Bell');
insert into mamodo values (31, 'Baransha', 'inganno', '6', 'Garza', 'giallo-messicano', 'Mamodo Millenari');
insert into mamodo values (32, 'Bago', 'fuoco', '4', 'Fredo', 'arancione chiaro', 'Kanchome');
insert into mamodo values (33, 'Vincent Bari', 'vortice', '12', 'Gustav', 'blu cobalto', 'Ponygon');
insert into mamodo values (34, 'Donpoccho', 'energia', '1', 'Goman', 'lime', 'Vincent Bari');
insert into mamodo values (35, 'Furigaro', 'ghiaccio', '4', 'Gerhart', 'celeste', 'Brago');
insert into mamodo values (36, 'Penny', 'acqua', '10', 'Uri', 'arancia', 'Mamodo Millenari');
insert into mamodo values (37, 'Byonko', 'melma', '5', 'Alvin', 'giallo-verde', 'Mamodo Millenari');
insert into mamodo values (38, 'Magister', 'magnetismo', '7', '-', 'blu-viola', 'Brago');
insert into mamodo values (39, 'Majirou', 'energia', '2', 'Nicholas', 'lime elettrica', 'Brago');
insert into mamodo values (40, 'Ted', 'rafforzamento', '9', 'Jido', 'blu sax', 'Gyaron');
insert into mamodo values (41, 'Earth', 'spada', '12', 'Elly', 'rosso-viola', 'Gorm');
insert into mamodo values (42, 'Koral Q', 'trasformazione', '8', 'Glubb', 'blu-celeste', 'Zatch Bell');
insert into mamodo values (43, 'Karudio', 'armatura', '4', 'Sauzaa', 'bianco-blu', 'Faudo');
insert into mamodo values (44, 'Rein', 'artiglio', '4', 'Kyle', 'verde malachite', 'Zatch Bell');
insert into mamodo values (45, 'Momon', 'inganno', '6', 'Elle', 'rosa-salmone', 'Rodeaux');
insert into mamodo values (46, 'Rodeaux', 'ala', '9', 'Chita', 'caffe', 'Purio');
insert into mamodo values (47, 'Riou', 'bestia', '11', 'Banikis', 'lime chiaro', 'Zeno Bell');
insert into mamodo values (48, 'Zaruchimu', 'buio', '8', 'Raushin', 'cedro', 'Ponygon');
insert into mamodo values (49, 'Hougan', 'fuoco', '2', 'Million', 'grigio urbano', 'Earth');
insert into mamodo values (50, 'Keith', 'laser', '8', 'Bern', 'miele', 'Vincent Bari');
insert into mamodo values (51, 'Buzurai', 'metallo', '9', 'Kazu', 'uva', 'Zatch Bell');
insert into mamodo values (52, 'Cherish', 'Cristallo', '8', 'Nicole', 'giallo sciolto', 'Zeno Bell');
insert into mamodo values (53, 'Riya', 'trasformazione', '11', 'Alishie', 'verde parrocchetto', 'Zaruchimu');
insert into mamodo values (54, 'Fango', 'fuoco', '8', 'Adler', 'geranio', 'Riya');
insert into mamodo values (55, 'Jedun', 'serpente', '8', 'Eskaruro', 'grigio lilla', 'Zatch Bell');
insert into mamodo values (56, 'Gyaron', 'armatura', '7', 'Harry jet', 'grigio antracite', 'Ted');
insert into mamodo values (57, 'Elzador', 'rafforzamento', '2', 'Abiira Sabiira', 'verde acqua', 'Vincent Bari');
insert into mamodo values (58, 'Ashuron', 'rafforzamento', '8', 'Riin Vise', 'vermiglio', 'Clear Note');
insert into mamodo values (59, 'Snail', 'unknown', '0', 'Unknown', 'unknown', 'Karudio');
insert into mamodo values (60, 'Maraion', 'unknown', '0', 'Unknown', 'unknown', 'Karudio');
insert into mamodo values (61, 'Rogue Viper', 'unknown', '0', 'Unknown', 'mais oro', 'Brago');
insert into mamodo values (62, 'Clear Note', 'annientamento', '16', 'Vino', 'trasparente', 'Zatch Bell');
insert into mamodo values (63, 'Gorm', 'camera nera', '6', 'Mir', 'ebano', 'Zatch Bell');
insert into mamodo values (64, 'Gani Fest', 'trasformazione', '1', 'Gentleman', 'blu spettro', 'Earth');